#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: pvc-sth-comet
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: gfiwire-storage-class-ebs
#  resources:
#    requests:
#      storage: "1Gi"
#
#---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sth-comet-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: sth-comet
  template:
    metadata:
      labels:
        app: sth-comet
    spec:
      containers:
      - name: sth-comet
        image: fiware/sth-comet:latest
#        imagePullPolicy: Never
        ports:
        - containerPort: 8666
          protocol: TCP
        env:
        - name: STH_HOST
          value: "0.0.0.0"
        - name: DB_URI
          value: "mongo:27017"
#        volumeMounts:
#        - mountPath: /opt/sth/conf
#          name: persistent-opt-sth-conf
#        - mountPath: /etc/localtime
#          name: persistent-localtime
#          readOnly: true
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8666
          timeoutSeconds: 2

#      nodeSelector:
#        scfw.cluster.id: stdap

#      volumes:
#      - persistentVolumeClaim:
#          claimName: pvc-sth-comet
#        name: persistent-opt-sth-conf
#      - hostPath:
#          path: /etc/localtime
#          type: FileOrCreate
#        name: persistent-localtime

---

apiVersion: v1
kind: Service
metadata:
  name: sth-comet
spec:
  type: ClusterIP
  ports:
  - port: 8666
    name: tcp8666to8666
    protocol: TCP
    targetPort: 8666
  selector:
    app: sth-comet

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sth-comet-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sth-comet-deployment
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75

